---
- name: Install and start Apache web server
  hosts: all
  become: yes  # escalates to root (if needed)
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

  
